### ISSUE TITLE
Installation unclear with Docker

### ISSUE THREAD

**Issue by itschrono** [SamuelTS/MongoDB-PHP-GUI#3]
Hello, I cannot get it to work with docker php-fpm 7.2.
=>  PHP Fatal error:  Uncaught Error: Class 'Controllers\LoginController' not found in routes.php

Should I install / enable another extension along mongodb ???
Thanks

**Comment by SamuelTS** [comment]
Hello, Did you run `composer install`?
And can you share your Docker filles?

**Comment by itschrono** [comment]
Dockerfile:
```dockerfile
FROM php:7.2-fpm


# Use the default production configuration
RUN mv "$PHP_INI_DIR/php.ini-production" "$PHP_INI_DIR/php.ini"

# Install Composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

RUN apt-get update
RUN pecl install mongodb
RUN apt-get install zip unzip
RUN docker-php-ext-enable mongodb

RUN rm -Rf /var/www/mongogui_src/
RUN mkdir -p /var/www/mongogui_src/
RUN mkdir -p /var/www/mongogui/
COPY ./src/* /var/www/mongogui_src/
WORKDIR /var/www/mongogui/

RUN mkdir -p /app
COPY run.sh /app/
# RUN composer install
# RUN composer update
# RUN composer dump-autoload --optimize

EXPOSE 9000
```

run.sh:
```bash
rm -Rf /var/www/mongogui/* && mkdir -p /var/www/mongogui/ && cp -R /var/www/mongogui_src/* /var/www/mongogui/ && composer install && composer dump-autoload --optimize && php-fpm
```

compose file:
```yaml
  mongogui:
    container_name: mongogui
    build: ./mongodb-php-gui
    command: "sh /app/run.sh"
    ports:
      - 9000:9000
    networks:
      - api-network
      - db-network
    volumes:
      - mongogui_volume:/var/www/mongogui
```
